INSERT INTO usr VALUES (1,'a', 'a', '$2b$10$Tp7f5YzlN4f3bH/.4hWbU.jmb7wPxmQ0luFpV/io.FnBxaMzIj3Zi');
INSERT INTO dev VALUES (1,'FAN',0,null);
INSERT INTO dev VALUES (2,'HEATER',0,null);
INSERT INTO dev VALUES (3,'LED',0,null);
INSERT INTO dev VALUES (4,'REAGROUP BUTTON',0,null);
INSERT INTO dev VALUES (5,'RGB_LED',0,'255:255:255');
INSERT INTO dev VALUES (6,'DHT',0,'00:00');
